In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
import pandas as pd

In [2]:
def d_plus(St, K, T, t, r, sigma):
    return (np.log(St / K) + r * (T - t)) / (sigma * np.sqrt(T - t)) + sigma/2 * np.sqrt(T - t)

def d_minus(St, K, T, t, r, sigma):
    return (np.log(St / K) + r * (T - t)) / (sigma * np.sqrt(T - t)) - sigma/2 * np.sqrt(T - t)

def blscallprice(St, K, T, t, r, sigma):
    return St *norm.cdf(d_plus(St, K, T, t, r, sigma)) - K * np.exp(-r*(T - t))*norm.cdf(d_minus(St, K, T, t, r, sigma))

def blsputprice(St, K, T, t, r, sigma):
    return  - St *norm.cdf(-d_plus(St, K, T, t, r, sigma)) + K * np.exp(-r*(T - t))*norm.cdf(-d_minus(St, K, T, t, r, sigma))

def delta(St, K, T, t, r, sigma):
  return norm.cdf(d_plus(St, K, T, t, r, sigma))

In [3]:
K = 50
r = 0.05
sigma = 0.2
miu = 0.13
T = 20/52
dt = 1/52

In [54]:
week_rate = 1.05**(1/52)

In [4]:
def price_simu():
  price = [49]
  for i in range(20):
    change = miu*dt + sigma*dt**0.5*np.random.normal()
    price.append(price[i]*(1+change))
  return price

In [5]:
def calculate_delta(price):
  delta_ = []
  for i in range(20):
    delta_.append(delta(price[i], 50, T, i/52, r, sigma))
  if(price[20] > K):
    delta_.append(1)
  else:
    delta_.append(0)
  delta_ = np.round(delta_, 5)
  return delta_

In [6]:
def calculate_cost(price, delta_):
  share_purchased = []
  cost_share = []
  cumulative_cost = []
  share_purchased.append(100000*delta_[0])
  cost_share.append(share_purchased[0] * price[0])
  cumulative_cost.append(cost_share[0])
  for i in range(1, 21):
    position_change = 100000*(delta_[i] - delta_[i-1])
    share_purchased.append(position_change)
    cost_share.append(position_change * price[i])
    cumulative_cost.append(cumulative_cost[i - 1]*week_rate + cost_share[i])
  return share_purchased, cost_share, cumulative_cost

In [52]:
price = price_simu()
delta_ = calculate_delta(price)
share_purchased, cost_share, cumulative_cost = calculate_cost(price, delta_)

In [53]:
df = pd.DataFrame(list(zip(price, delta_, share_purchased, cost_share, cumulative_cost)),
               columns =['Stock Price', 'Delta', 'Shares Purchased', 'Cost of Shares Purchased', 'Cumulative Cost with Interest'])
df

,Stock Price,Delta,Shares Purchased,Cost of Shares Purchased,Cumulative Cost with Interest
0,49.000000,0.52160,52160.0,2.555840e+06,2.555840e+06
1,50.861632,0.63792,11632.0,5.916225e+05,3.149862e+06
2,50.737198,0.62942,-850.0,-4.312662e+04,3.109692e+06
3,50.305594,0.60002,-2940.0,-1.478984e+05,2.964713e+06
4,48.896670,0.49721,-10281.0,-5.027067e+05,2.464789e+06
5,49.097505,0.50734,1013.0,4.973577e+04,2.516838e+06
6,49.723294,0.55098,4364.0,2.169925e+05,2.736193e+06
7,47.725705,0.38571,-16527.0,-7.887627e+05,1.949999e+06
8,47.500938,0.35736,-2835.0,-1.346652e+05,1.817165e+06
9,49.654705,0.53412,17676.0,8.776966e+05,2.696567e+06
10,47.421070,0.32624,-20788.0,-9.857892e+05,1.713309e+06
11,47.684791,0.33571,947.0,4.515750e+04,1.760075e+06
12,48.531456,0.40411,6840.0,3.319552e+05,2.093682e+06
13,49.637946,0.51172,10761.0,5.341539e+05,2.629801e+06
14,48.296855,0.34781,-16391.0,-7.916338e+05,1.840636e+06
15,46.486756,0.14316,-20465.0,-9.513515e+05,8.910127e+05
16,44.168968,0.01624,-12692.0,-5.605925e+05,3.312566e+05
17,44.779713,0.01351,-273.0,-1.222486e+04,3.193427e+05
18,47.570248,0.11480,10129.0,4.818390e+05,8.014815e+05
19,48.220210,0.10414,-1066.0,-5.140274e+04,7.508311e+05
20,48.221959,0.00000,-10414.0,-5.021835e+05,2.493525e+05

In [44]:
price1 = price_simu()
delta_1 = calculate_delta(price1)
share_purchased1, cost_share1, cumulative_cost1 = calculate_cost(price1, delta_1)

In [55]:
df1 = pd.DataFrame(list(zip(price1, delta_1, share_purchased1, cost_share1, cumulative_cost1)),
               columns =['Stock Price', 'Delta', 'Shares Purchased', 'Cost of Shares Purchased', 'Cumulative Cost with Interest'])

In [56]:
df1

,Stock Price,Delta,Shares Purchased,Cost of Shares Purchased,Cumulative Cost with Interest
0,49.000000,0.52160,52160.0,2.555840e+06,2.555840e+06
1,49.941818,0.58002,5842.0,2.917601e+05,2.849999e+06
2,48.690847,0.49220,-8782.0,-4.276030e+05,2.425072e+06
3,50.954530,0.64263,15043.0,7.665090e+05,3.193857e+06
4,50.809857,0.63269,-994.0,-5.050500e+04,3.146350e+06
5,48.717485,0.47850,-15419.0,-7.511749e+05,2.398129e+06
6,48.247764,0.43559,-4291.0,-2.070312e+05,2.193349e+06
7,47.054487,0.33281,-10278.0,-4.836260e+05,1.711782e+06
8,46.107149,0.24968,-8313.0,-3.832887e+05,1.330100e+06
9,46.893804,0.29589,4621.0,2.166963e+05,1.548045e+06
10,49.943009,0.55586,25997.0,1.298368e+06,2.847866e+06
11,50.067636,0.56429,843.0,4.220702e+04,2.892747e+06
12,47.679015,0.31967,-24462.0,-1.166324e+06,1.729138e+06
13,47.309545,0.26587,-5380.0,-2.545254e+05,1.476236e+06
14,46.382529,0.16193,-10394.0,-4.821000e+05,9.955216e+05
15,47.743466,0.26235,10042.0,4.794399e+05,1.475896e+06
16,48.765620,0.36183,9948.0,4.851204e+05,1.962402e+06
17,50.687571,0.64370,28187.0,1.428731e+06,3.392974e+06
18,51.088097,0.73155,8785.0,4.488089e+05,3.844968e+06
19,52.570524,0.96828,23673.0,1.244502e+06,5.093080e+06
20,53.383663,1.00000,3172.0,1.693330e+05,5.267194e+06

(i) $\Delta$ equals to $\Phi(d_1)$, while $d_1 = \frac{log(St/K)}{\sigma\sqrt{T-t}} + (r - \frac{\sigma^2}{2}) *\frac{\sqrt{T-t}}{\sigma}$. As the time gets close to the expiration, the later term of $d_1$ would goes to zero, and the first term would goes to positive infinity if $S_T > K$, negative infinity if $S_T < K$.   

As $\Phi(\infty) = 1, \Phi(-\infty) = 0$:

*   $S_T > K, \Delta = 1$, position equals $100,000$, as under the situation that $S_T > K$, clearly the option would be exercised, the hedger should have a full covered position,
*   $S_T < K, \Delta = 0$, position equals $0$, as under the situation that $S_T < K$, obviously the option would not be exercised, it would be fine for the hedger to hold a naked position.

And this only depends on the price at expiration which would decide whether the option would be exercised, thus independent of the realized path of price over $[0, T]$.

(ii) According to the two simulation run above, the total cost at first scenario is about $\$267194$ given the option would be exercised, and the total cost is about $\$249353$ given the option would not be exercised. Both are close to the Black-Scholes price after continuous compounding the $\$240000$ to the expiration date, which $= 240000*1.05^\frac{20}{52} = \$ 244546$.